### ISSUE TITLE
Broken link for Yao-Jen Chang in the sed $HOME

### ISSUE THREAD

**Issue by gudermez** [aureliojargas/sed.sf.net#1]
In the sed.sf.net site, when we try to click the link under the :sedlovers heading
by the name of Yao-Jen Chang the link is found to be missing/brokern.

Please fix this broken/missing link.

Best Regards,
Gudermez

**Comment by aureliojargas** [comment]
Thanks for the report!

I couldn't find the new URL for the site, so I've changed the link to the latest snapshot available in the Internet Archive: http://web.archive.org/web/20141115192529/http://main.rtfiber.com.tw/~changyj/sed/
