### ISSUE TITLE
All scripts that are not colored are missing

### ISSUE THREAD

**Issue by ericmarceau-rogers** [aureliojargas/sed.sf.net#13]
Ex.  http://sed.sf.net/grabbag/scripts/*.txt   always reports error.  

i.e.  http://sed.sf.net/grabbag/scripts/cal.sh.txt

Even trying   https://sed.sourceforge.io/local/scripts/cal.sh.txt   does not succeed !!!

**Comment by aureliojargas** [comment]
Hi @ericmarceau-rogers, thanks for the report.

Unfortunately, we lost the grabbag area from the website (see #11). I'm still in the process of trying to recover it.

All the scripts in the `local` folder can be found here: https://github.com/aureliojargas/sed.sf.net/tree/master/local/scripts

**Comment by aureliojargas** [comment]
@ericmarceau-rogers since PR #15 the scripts you've mentioned are now restored to their original URLs.
