### ISSUE TITLE
docs URL update for "Sed by example, Part 1"

### ISSUE THREAD

**Issue by latebeer** [aureliojargas/sed.sf.net#2]
The URL for the docs article "Sed by example, Part 1 by Daniel Robbins" should be <a href="http://www.ibm.com/developerworks/linux/library/l-sed1/index.html">http://www.ibm.com/developerworks/linux/library/l-sed1/index.html</a>

**Comment by aureliojargas** [comment]
Fixed. Thanks for the report @latebeer!
