### ISSUE TITLE
broken download site

### ISSUE THREAD

**Issue by skulakowski** [aureliojargas/sed.sf.net#3]
http://www.student.northpark.edu/pemente/sed/sed3028a.zip

(couldn't figure out how to pull request. sorry.)

**Comment by aureliojargas** [comment]
No problem @skulakowski, thanks for the report, it helped!

**Comment by skulakowski** [comment]
Happy to help.
Susan

On Sun, 05 Apr 2015 06:39:35 -0400, Aurelio Jargas  
notifications@github.com wrote:

> No problem @skulakowski, thanks for the report, it helped!
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Susan Kulakowski

skulakowski@me.com
1 (201) 647-0977 mobile
1 (201) 743-8380 conference

Using Opera's mail client: http://www.opera.com/mail/

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
