### ISSUE TITLE
remccoms3.sed  fails on nested comments

### ISSUE THREAD

**Issue by xtforever** [aureliojargas/sed.sf.net#5]
It says:
# Remove C and C++ comments, by Brian Hiles (brian_hiles@rocketmail.com)

the script works fine but fails over nested commands.

CREATE TABLE IF NOT EXISTS  stoer_text
(
        code           smallint                not null,  /* code */
        bezeichnung    char(80)                not null,
constraint pk_sx primary key (code) 
/* muli
line /*
code
*/
*/
);

/* code 

*/

./rmcoms.sh  <test.sql

CREATE TABLE IF NOT EXISTS  stoer_text
(
        code           smallint                not null,  
        beze           char(80)                not null,
constraint pk_sx primary key (code) 

*/  <-- ups
);

**Comment by aureliojargas** [comment]
I'm closing this, since this repo is for the website sources, and the script author email is available.
