### ISSUE TITLE
Non-charset characters are not recognized.

### ISSUE THREAD

**Issue by Sur3** [aureliojargas/sed.sf.net#7]
sed doesn't recognize non-charset characters as . (dot), eg with `LC_CTYPE=en_US.UTF-8`:
```
# printf "ABCD\n" | sed 's/B.*C//'
Output: AD
# printf "AB\x8eCD\n" | sed 's/B.*C//'
Output: AB�CD
```
I also tried something like `[^E]*` instead of `.*` but that also does not work.
I think sed should recognize \x8e is not a C or newline even though it's not in the character set.
With
```
# printf "AB\x8eCD\n" | LC_CTYPE=C sed 's/B.*C//'
Output: AD
```
it works but, that's a bit non-intuitive, because normally one wants to have UTF8-charset and sed to function correctly anyway or is there an other regex similar to . that can recognize such characters?

**Comment by aureliojargas** [comment]
Hi @Sur3, this project is only a website with links to sed scripts and documentation. You can try to send your message to the mailing list: http://groups.yahoo.com/group/sed-users/
