### ISSUE TITLE
Link to "http://www.sed-book.com" leads to a home inspector website

### ISSUE THREAD

**Issue by AlexDikelsky** [aureliojargas/sed.sf.net#9]
The "Definitive Guide to sed" link in the :books section links to "http://www.sed-book.com", which used to be about sed, but isn't anymore. The link could go to "https://web.archive.org/web/20160504071135/http://www.sed-book.com/" instead.

**Comment by aureliojargas** [comment]
Thank you @AlexDikelsky! It seems that the new URL is now https://www.ehdp.com/press/sed-book/. I'll fix it in the next commit.
